### ISSUE TITLE
List Index shows Lists with their names

### ISSUE THREAD

**Issue by FifthSurprise** [Nakirendral/ListApp#13]
# Feature
When you navigate to `/lists`, you see all of the Lists with each List's name.

- The Lists Controller's #index method needs to capture all of the lists (`List.all`) and pass that in a variable to the index view.  See: https://guides.rubyonrails.org/layouts_and_rendering.html
-  The [Lists Index View](https://github.com/Nakirendral/ListApp/blob/master/app/views/lists/index.html.erb) needs to be updated to show each list's `list_name`

Notes:
The routes.rb already has `resources :lists` so navigate to `/lists` locally should work.

**Comment by Nakirendral** [comment]
![image](https://user-images.githubusercontent.com/3393776/94176073-900acb80-fe65-11ea-80ee-3505280fd1f5.png)

I believe I got the /list route working but it is ugly as sin.
