### ISSUE TITLE
Show an individual List via /lists/:id

### ISSUE THREAD

**Issue by FifthSurprise** [Nakirendral/ListApp#14]
# Feature

A user is able to navigate to view a single list.

If you create a List via the console (Ex.  List.create(list_name: "My first List"), then you should be able to navigate to that List in the UI via `/lists/:id` where the :id` is the id of the newly created List.

`/lists/:id` should render the List with the List's name at the top of the page.  This will be a show controller method.

-  Create a show method in the ListsController
-  In the show method, use the passed in id parameter to find the list
-  Store the resulting list in @list
-  Create a `show.html.erb` in the `app/views/lists` to show a single List.  Inside it should show the List's name in the body.

**Comment by FifthSurprise** [comment]
This issue is a little meatier and it might make sense to break it down into the bullet points I suggested.  If you prefer to make smaller PR's, you can create separate branch (ex. `show_list`) off of master to hold all of this issue's work but then make PR's into it.  Then when you have completed all of the parts of this issue, you can make a PR from said branch (`show_list`) into Master.

**Comment by Nakirendral** [comment]
I believe the issue is resolved. The page is ugly as sin but it does allow for viewing the List item via lists/id!
