### ISSUE TITLE
Editing a List's Name

### ISSUE THREAD

**Issue by FifthSurprise** [Nakirendral/ListApp#20]
A user should be able to edit a List's Name.

This means creating edit/update methods and the related views.

- List#edit
- List#update
- Tests

Notes:
Routes already exists in routes.rb because of `resources: lists`

**Comment by yashdave00** [comment]
Hi Can i take this up? Im a new contributor but i have experience

**Comment by Nakirendral** [comment]
I made PRs of the updates I made to get the edit list functionality working! I know it is ugly but I am happy with this Ugly Baby!
