### ISSUE TITLE
A user can view an individual Entry

### ISSUE THREAD

**Issue by FifthSurprise** [Nakirendral/ListApp#24]
There needs to be a path for an individual Entry to be visible by the user.  While Issue #23 will allow the user to see an Entry on the List, we'll eventually want to manipulate those entries (ie. create, edit, destroy).  To start we'll need to be able to look at the details of an individual entry.

For example:  

You may have a List with :id of 2 an an Entry with id 3.

With #23 we'll see the full list of entries on List#show.  But If I want to look at an individual entry, we access it via a route such as:
`lists/2/entries/3`
The way to set this is up is with [Nested Resources.](https://guides.rubyonrails.org/routing.html#nested-resources)

You will need to construct the following:
- Nested route for the #show for an Entry
- Entry Controller with a show method
- Entries/show.html.erb
  - Displays the Entry's content
  - Displays the Title of the Entry's List
  - Has a Link back to the List
- Tests

**Comment by Nakirendral** [comment]
I believe this has been resolved via PR #42
