### ISSUE TITLE
Study: Git

### ISSUE THREAD

**Issue by sllewely** [Nakirendral/ListApp#5]
Take notes on your commonly used git commands so you can go back for reference.

I put together these notes for other people who were learning that you can use --
https://github.com/sllewely/notes/tree/master/git

But any time I think to myself "I wish I could do x" in git, I would have a google, because there's probably a way to do it!  And you'll learn because it took work :)

**Comment by Nakirendral** [comment]
Whoop! Meant to close the issue because I wrote a few things using markdown within the wiki!
